version: "3.9"
networks:
  pyciemss:
    driver: bridge
    name: pyciemss
services:
  api:
    container_name: pyciemss-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn server:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8010:8000"
    env_file:
      - ../api.env
    networks:
      - pyciemss
    depends_on:
      - redis
    volumes:
      - $PWD/api:/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - pyciemss
  rqworker:
    container_name: pyciemss-worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../api.env
    depends_on:
      - redis
      - api
    networks:
      - pyciemss
