FROM python:3.10

WORKDIR /
RUN pip install --no-cache-dir poetry==1.5.1
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry config virtualenvs.create false && \
    poetry install --no-root --no-cache

COPY service service
COPY README.md README.md

RUN poetry install

ENV REDIS_HOST redis
ENV REDIS_PORT 6379

WORKDIR /service
CMD uvicorn server:app --reload --host 0.0.0.0 --port 8000
