version: "3.9"
networks:
  pyciemss:
    driver: bridge
    name: pyciemss
  terarium:
    external: true
services:
  api:
    container_name: pyciemss-api-ciemss
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8010:8000"
    env_file:
      - ../.env
    networks:
      - pyciemss
      - terarium
    volumes:
      - $PWD/service:/service
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rqworker:
    container_name: pyciemss-worker-ciemss
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    env_file:
      - ../.env
    depends_on:
      - api
    networks:
      - pyciemss
      - terarium
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis-ciemss
    image: redis:7-alpine
    ports:
      - "6666:6379"





