---
name: Formatting
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'dev/*']

jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1
      - name: Create environment
        run: poetry install
      - name: Black
        run: poetry run black . --check --verbose
      - name: Ruff
        run: poetry run ruff .
