---
# Automatically build Docker images on changes to main and push them to a
# Container Registry using HCL Bake file.

name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  # Call the Tag Generator to generate an image tag to use
  tag-generator:
    uses: darpa-askem/.github/.github/workflows/tag-generator.yaml@main

  # Build and Publish all targets associated with specified group
  bake:
    needs:
      - tag-generator
    uses: darpa-askem/.github/.github/workflows/bake-publish.yml@main
    with:
      file: 'docker/docker-bake.hcl'
      group: 'prod'
      registry: 'ghcr.io'
      no-cache: true
      organization: ${{ github.repository_owner }}
      tag: ${{ needs.tag-generator.outputs.tag }}
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # Execute simulation-integration reporting
  simulation-integration:
    runs-on: ubuntu-latest
    needs: 
      - bake
    steps:
      - name: Report
        env: 
          GITHUB_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          gh workflow run report.yaml --repo DARPA-ASKEM/simulation-integration --ref main
